GET http://192.168.0.97:3000/chart

###
POST http://192.168.0.97:3000/chart
Content-Type: application/json

{
    "title": "金融大数据",
    "user": "1234"
}

###

GET http://192.168.0.97:3000/demo/percent

###

GET http://192.168.0.97:3000/demo/pv
